(ns record-fixtures
  "Regenerate test/ogg/fixtures.cljc from real Ogg files produced by ffmpeg.

       nbb tools/record_fixtures.cljs

   The portable suite must assert conformance against real containers on
   ClojureScript, where there is no shell and no filesystem, so short reference
   files are recorded here once and checked in as base64.

   Every recorded file is confirmed decodable by ffmpeg before being written, so
   a fixture can never be something the reference itself rejects."
  (:require ["node:child_process" :as cp]
            ["node:fs" :as fs]
            [kotoba.lang.text :as str]))

(def ^:private cases
  ;; [name encoder] — 0.12 s of a sine wave keeps each file under 4 KB while
  ;; still producing multiple pages and a multi-page-spanning header packet
  [["opus" "libopus"]
   ["vorbis" "libvorbis"]
   ["flac" "flac"]])

(defn- sh [cmd args]
  (let [r (cp/spawnSync cmd (clj->js args) #js {:encoding "buffer"})]
    (when-not (zero? (.-status r))
      (throw (ex-info (str cmd " failed") {:stderr (str (.-stderr r))})))
    r))

(defn- encode [encoder path]
  (sh "ffmpeg" ["-hide_banner" "-v" "error" "-f" "lavfi"
                "-i" "sine=frequency=440:duration=0.12"
                "-c:a" encoder "-f" "ogg" path "-y"])
  ;; the reference must accept its own output before we record it
  (sh "ffmpeg" ["-hide_banner" "-v" "error" "-i" path "-f" "null" "-"])
  (vec (js/Array.from (fs/readFileSync path))))

(defn- b64 [bytes] (.toString (.from js/Buffer (clj->js bytes)) "base64"))

(defn -main []
  (let [recorded (mapv (fn [[name encoder]]
                         [name (encode encoder (str "/tmp/ogg-fixture-" name ".ogg"))])
                       cases)
        lines (concat
               ["(ns ogg.fixtures"
                "  \"Real Ogg files produced by ffmpeg, recorded so the portable suite can"
                "   assert conformance on both runtimes with no shell and no filesystem."
                ""
                "   Each entry is base64 of a complete physical stream: 0.12 s of a sine"
                "   wave, which is enough for multiple pages and a header packet."
                ""
                "   Generated by tools/record_fixtures.cljs — do not hand-edit.\")"
                ""
                "(def files"
                "  {"]
               (mapcat (fn [[name bytes]]
                         [(str "   \"" name "\"")
                          (str "   \"" (b64 bytes) "\"")])
                       recorded)
               ["   })"])]
    (fs/writeFileSync "test/ogg/fixtures.cljc" (str (str/join "\n" lines) "\n"))
    (println "wrote test/ogg/fixtures.cljc"
             (str "(" (str/join ", " (map (fn [[n b]] (str n " " (count b) "B")) recorded)) ")"))))

(-main)
